### ISSUE TITLE
【現状報告】

### ISSUE THREAD

**Issue by kaizanakasato** [4QOneMonthProducts/question-page#1]
現状取りかかっていること
　・「TopPage」のチェックボックスのデザイン変更

未完成
　・「ナビゲーションメニュー」のデザイン・レスポンシブ設定
　・「MyPage」の問題投稿結果のデザイン調整

連絡が遅くなってしまい申し訳ないです・・・

**Comment by yseTakuma-Nakagame** [comment]
レスが遅くなって申し訳ない  
いま確認した。

> 「TopPage」のチェックボックスのデザイン変更

終わった？


> 「ナビゲーションメニュー」のデザイン・レスポンシブ設定

こちらで一時対応してみます。


> 「MyPage」の問題投稿結果のデザイン調整

問題投稿結果というのがわからない。具体的には、何行目くらい？

**Comment by kaizanakasato** [comment]
【報告】
ハンバーガメニューを除いた以下の作業が終わりましたので、
すべてのファイルはGitHubに上げときました。

ハンバーガメニューに関しては、
本日中には実装が難しいと判断したため
翌日以降に取り掛かりたいと考えています・・・

**Comment by yseTakuma-Nakagame** [comment]
ハンバーガーメニューは石黒さんがやっているのではなくて？

**Comment by kaizanakasato** [comment]
一応、メニュー事体は完成したから、
こちらで実装する形だけれども、複雑すぎて今日中は厳しいです。

**Comment by yseTakuma-Nakagame** [comment]
ソースはGitにある？
こちらで実装します

**Comment by kaizanakasato** [comment]
全部あります、石黒さんが使っていたサイトURL貼っときます。
・http://www.webdesignleaves.com/wp/jquery/1384/

**Comment by kaizanakasato** [comment]
丸投げになってしまい本当に申し訳ない

**Comment by yseTakuma-Nakagame** [comment]
了解、助かる

ええんやで、中里さんは頑張ってくれてる

**Comment by kaizanakasato** [comment]
いえいえ、とんでもない
体調に気をつけて残りの作業をお願いします。

**Comment by yseTakuma-Nakagame** [comment]
頼まれた
あとで、例のごとく各ページヘの調整とか発生するだろうからスタンバってて

**Comment by yseTakuma-Nakagame** [comment]
ハンバーガーメニューのHTMLはいずこに？

**Comment by kaizanakasato** [comment]
ごめんなさい、上げなおしました

**Comment by yseTakuma-Nakagame** [comment]
確認した
ありがとう

**Comment by kaizanakasato** [comment]
遅くなってしまい申し訳ない

**Comment by yseTakuma-Nakagame** [comment]
なんとかなるべ
